### ISSUE TITLE
form select  not working

### ISSUE THREAD

**Issue by eturerer** [materialstyle/materialstyle#115]
### Prerequisites

- [X] I have [searched](https://github.com/materialstyle/materialstyle/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/materialstyle/materialstyle/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

the example does not work https://jsfiddle.net/613za7mL/

### Reduced test cases

<!DOCTYPE html>
<html>

<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@materialstyle/materialstyle@3.1.1/dist/css/materialstyle.min.css">

    <title>Material Style</title>
</head>

<body>

    <div class="form-floating">
        <select class="form-select">
            <option value="" label="blank option"></option>
            <option value="1">Option 1</option>
            <option value="2">Option 2</option>
            <option value="3">Option 3</option>
            <option value="4">Option 4</option>
        </select>
        <label>Select One</label>
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/@materialstyle/materialstyle@3.1.1/dist/js/materialstyle.min.js"></script>

</body>

</html>

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Material Style are you using?

3.1.1

**Comment by nkdas91** [comment]
Hi @eturerer 

You have to initialize the Select component using Javascript: https://materialstyle.github.io/materialstyle/3.1/forms/select-fields/#javascript

```javascript
// Initialize
var selectList = [].slice.call(document.querySelectorAll('.form-select'))
var selectFields = selectList.map(function (select) {
  return new materialstyle.SelectField(select)
})
```
